#!/bin/sh -e
# postinst script for sparqled
#
# see: dh_installdeb(1)

. /usr/share/debconf/confmodule

rm -f /var/lib/tomcat6/webapps/sparqled.war
rm -rf /var/lib/tomcat6/webapps/sparqled
cp /usr/share/sparqled/sparqled.war /var/lib/tomcat6/webapps



echo "---- ending postinst $@"

